/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.
import * as github_com_hackaTUM_GameOfStonks_services_stonks from './stonks'; // ../frontend/src/services/client.ts to ../frontend/src/services/stonks.ts

export class StonksClient {
	public static defaultEndpoint = "/service/stonks";
	constructor(
		public transport:<T>(method: string, data?: any[]) => Promise<T>
	) {}
	async hello(name:string):Promise<{ret:string; ret_1:github_com_hackaTUM_GameOfStonks_services_stonks.Err|null}> {
		const response = await this.transport<{0:string; 1:github_com_hackaTUM_GameOfStonks_services_stonks.Err|null}>("Hello", [name])
		return {ret : response[0], ret_1 : response[1]};
	}
	async helloInterface(anything:any, anythingMap:Record<string,any>|null, anythingSlice:Array<any>|null):Promise<void> {
		await this.transport<void>("HelloInterface", [anything, anythingMap, anythingSlice])
	}
	async helloNumberMaps(intMap:Record<number,string>|null):Promise<Record<number,string>|null> {
		return (await this.transport<{0:Record<number,string>|null}>("HelloNumberMaps", [intMap]))[0]
	}
	async helloScalarError():Promise<github_com_hackaTUM_GameOfStonks_services_stonks.ScalarError|null> {
		return (await this.transport<{0:github_com_hackaTUM_GameOfStonks_services_stonks.ScalarError|null}>("HelloScalarError", []))[0]
	}
}