/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.
import * as github_com_hackaTUM_GameOfStonks_services_stonks from './stonks'; // ../frontend/src/services/stonks.ts to ../frontend/src/services/stonks.ts
// github.com/hackaTUM/GameOfStonks/services/stonks.Err
export interface Err {
	message:string;
}
// github.com/hackaTUM/GameOfStonks/services/stonks.ScalarError
export type ScalarError = string
// end of common js