/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.
import * as github_com_hackaTUM_GameOfStonks_services_stonks from './vo-stonks'; // ./frontend/src/services/stonk-client.ts to ./frontend/src/services/vo-stonks.ts

export class StonksServiceClient {
	public static defaultEndpoint = "/service/stonks";
	constructor(
		public transport:<T>(method: string, data?: any[]) => Promise<T>
	) {}
	async getStonkInfo(id:string):Promise<{ret:github_com_hackaTUM_GameOfStonks_services_stonks.StonkInfo; ret_1:github_com_hackaTUM_GameOfStonks_services_stonks.Err|null}> {
		const response = await this.transport<{0:github_com_hackaTUM_GameOfStonks_services_stonks.StonkInfo; 1:github_com_hackaTUM_GameOfStonks_services_stonks.Err|null}>("GetStonkInfo", [id])
		return {ret : response[0], ret_1 : response[1]};
	}
	async hello(name:string):Promise<{ret:string; ret_1:github_com_hackaTUM_GameOfStonks_services_stonks.Err|null}> {
		const response = await this.transport<{0:string; 1:github_com_hackaTUM_GameOfStonks_services_stonks.Err|null}>("Hello", [name])
		return {ret : response[0], ret_1 : response[1]};
	}
	async helloInterface(anything:any, anythingMap:Record<string,any>|null, anythingSlice:Array<any>|null):Promise<void> {
		await this.transport<void>("HelloInterface", [anything, anythingMap, anythingSlice])
	}
	async helloNumberMaps(intMap:Record<number,string>|null):Promise<Record<number,string>|null> {
		return (await this.transport<{0:Record<number,string>|null}>("HelloNumberMaps", [intMap]))[0]
	}
	async helloScalarError():Promise<github_com_hackaTUM_GameOfStonks_services_stonks.ScalarError|null> {
		return (await this.transport<{0:github_com_hackaTUM_GameOfStonks_services_stonks.ScalarError|null}>("HelloScalarError", []))[0]
	}
	async newUser(name:string):Promise<github_com_hackaTUM_GameOfStonks_services_stonks.Err|null> {
		return (await this.transport<{0:github_com_hackaTUM_GameOfStonks_services_stonks.Err|null}>("NewUser", [name]))[0]
	}
	async startSession(id:string):Promise<{ret:Array<github_com_hackaTUM_GameOfStonks_services_stonks.User>|null; ret_1:github_com_hackaTUM_GameOfStonks_services_stonks.Err|null}> {
		const response = await this.transport<{0:Array<github_com_hackaTUM_GameOfStonks_services_stonks.User>|null; 1:github_com_hackaTUM_GameOfStonks_services_stonks.Err|null}>("StartSession", [id])
		return {ret : response[0], ret_1 : response[1]};
	}
}