/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.
import * as github_com_hackaTUM_GameOfStonks_services_stonks from './vo-stonks'; // ./frontend/src/services/vo-stonks.ts to ./frontend/src/services/vo-stonks.ts
// github.com/hackaTUM/GameOfStonks/services/stonks.Err
export interface Err {
	message:string;
}
// github.com/hackaTUM/GameOfStonks/services/stonks.Match
export interface Match {
	UserSell:string;
	UserBuy:string;
	Quantity:number;
	TimeStamp:number;
}
// github.com/hackaTUM/GameOfStonks/services/stonks.Order
export interface Order {
	User:string;
	OrderType:github_com_hackaTUM_GameOfStonks_services_stonks.OrderType;
	Quantity:number;
	TimeStamp:number;
}
// github.com/hackaTUM/GameOfStonks/services/stonks.OrderType
export type OrderType = string
// github.com/hackaTUM/GameOfStonks/services/stonks.ScalarError
export type ScalarError = string
// github.com/hackaTUM/GameOfStonks/services/stonks.StonkInfo
export interface StonkInfo {
	ID:string;
	History:Array<github_com_hackaTUM_GameOfStonks_services_stonks.Match>|null;
	Orders:Array<github_com_hackaTUM_GameOfStonks_services_stonks.Order>|null;
}
// github.com/hackaTUM/GameOfStonks/services/stonks.User
export interface User {
	Name:string;
}
// end of common js